server.port=8081

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/eumyurato?allowMultiQueries=true&useSSL=false}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml
mybatis.type-aliases-package=com.e114.e114.eumyuratodemo1

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=C:/uploads

com.example.upload.path.profileImg=C:/uploads

#GCP Storage
spring.cloud.gcp.credentials.location=${GCP_CREDENTIALS_LOCATION:}
spring.cloud.gcp.credentials.project-id=${GCP_PROJECT_ID:}
spring.cloud.gcp.bucket=${GCP_BUCKET:}

spring.cloud.gcp.storage.credentials.location=${GCP_CREDENTIALS_LOCATION:}
spring.cloud.gcp.storage.credentials.project-id=${GCP_PROJECT_ID:}
spring.cloud.gcp.storage.bucket=${GCP_BUCKET:}

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=utf-8
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
